// Pulls active listings from your Etsy shop via the Etsy Open API v3
// and writes them to ../data/products.json for the static site to render.
//
// Usage:
//   1. Copy ../.env.example to ../.env and fill in ETSY_API_KEY (and
//      ETSY_SHOP_NAME if your shop name isn't MicknackStacks).
//   2. From the Website folder: npm install && npm run sync
//
// Only public, read-only endpoints are used (findShops, active listings),
// so no OAuth login flow is needed — the API key alone is enough.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

// In CI (e.g. GitHub Actions), ETSY_API_KEY is injected as a real
// environment variable from a secret — no .env file involved. Locally, we
// fall back to reading ../.env so you don't have to export env vars by hand.
function loadEnv() {
  if (process.env.ETSY_API_KEY) {
    return {
      ETSY_API_KEY: process.env.ETSY_API_KEY,
      ETSY_SHOP_NAME: process.env.ETSY_SHOP_NAME,
    };
  }

  const envPath = join(ROOT, ".env");
  if (!existsSync(envPath)) {
    console.error(
      "Missing .env file. Copy .env.example to .env and add your ETSY_API_KEY first."
    );
    process.exit(1);
  }
  const env = {};
  for (const line of readFileSync(envPath, "utf8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    env[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
  }
  return env;
}

const env = loadEnv();
const API_KEY = env.ETSY_API_KEY;
const SHOP_NAME = env.ETSY_SHOP_NAME || "MicknackStacks";

if (!API_KEY) {
  console.error("ETSY_API_KEY is not set in .env");
  process.exit(1);
}

const BASE = "https://openapi.etsy.com/v3/application";
const headers = { "x-api-key": API_KEY };

async function etsyGet(path) {
  const res = await fetch(`${BASE}${path}`, { headers });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Etsy API ${res.status} on ${path}: ${body}`);
  }
  return res.json();
}

async function findShopId(shopName) {
  const data = await etsyGet(`/shops?shop_name=${encodeURIComponent(shopName)}`);
  if (!data.results || data.results.length === 0) {
    throw new Error(`No Etsy shop found for name "${shopName}"`);
  }
  return data.results[0].shop_id;
}

async function fetchAllActiveListings(shopId) {
  const listings = [];
  const limit = 100;
  let offset = 0;
  while (true) {
    const page = await etsyGet(
      `/shops/${shopId}/listings/active?limit=${limit}&offset=${offset}`
    );
    listings.push(...page.results);
    if (page.results.length < limit) break;
    offset += limit;
  }
  return listings;
}

// The bulk active-listings endpoint ignores `includes=Images`, so photos have
// to be fetched per listing.
async function fetchListingImages(listingId) {
  try {
    const data = await etsyGet(`/listings/${listingId}/images`);
    return (data.results || [])
      .sort((a, b) => a.rank - b.rank)
      .map((img) => img.url_fullxfull || img.url_570xN)
      .filter(Boolean);
  } catch (err) {
    console.warn(`Could not fetch images for listing ${listingId}: ${err.message}`);
    return [];
  }
}

function normalizeListing(listing, images) {
  return {
    listing_id: String(listing.listing_id),
    title: listing.title,
    price: (listing.price.amount / listing.price.divisor).toFixed(2),
    currency_code: listing.price.currency_code,
    url: listing.url,
    description: listing.description,
    images: images.length ? images : ["assets/products/placeholder.svg"],
    tags: listing.tags || [],
  };
}

async function main() {
  console.log(`Looking up shop "${SHOP_NAME}"...`);
  const shopId = await findShopId(SHOP_NAME);

  console.log(`Fetching active listings for shop_id ${shopId}...`);
  const rawListings = await fetchAllActiveListings(shopId);
  console.log(`Found ${rawListings.length} active listing(s).`);

  console.log("Fetching listing images...");
  const listings = [];
  for (const listing of rawListings) {
    const images = await fetchListingImages(listing.listing_id);
    listings.push(normalizeListing(listing, images));
  }

  const output = {
    shop_name: SHOP_NAME,
    shop_url: `https://www.etsy.com/shop/${SHOP_NAME}`,
    synced_at: new Date().toISOString(),
    listings,
  };

  const outPath = join(ROOT, "data", "products.js");
  const banner =
    "// Auto-generated by scripts/sync-etsy.js — do not hand-edit, it will be overwritten.\n";
  writeFileSync(outPath, `${banner}window.MICKNACK_PRODUCTS = ${JSON.stringify(output, null, 2)};\n`);
  console.log(`Wrote ${output.listings.length} listing(s) to ${outPath}`);
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
